# Generated by Django 5.2.17 on 2026-10-01 03:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Po',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nomor', models.CharField(max_length=80, unique=True)),
                ('produk', models.CharField(blank=True, max_length=160)),
                ('tgl_order', models.DateField(blank=True, null=True)),
                ('pemakaian_std', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('selesai', models.BooleanField(default=False)),
                ('catatan', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('purchasing', 'Purchasing'), ('direktur', 'Direktur'), ('admin', 'Admin')], default='direktur', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('waktu', models.DateTimeField(default=django.utils.timezone.now)),
                ('aksi', models.CharField(max_length=60)),
                ('objek', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('kind', models.CharField(choices=[('vendor', 'Vendor'), ('cmt', 'CMT'), ('material', 'Bahan'), ('color', 'Warna'), ('warehouse', 'Gudang')], max_length=12)),
                ('name', models.CharField(max_length=160)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
                'constraints': [models.UniqueConstraint(models.F('kind'), django.db.models.functions.text.Lower('name'), name='master_kind_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('nomor', models.CharField(max_length=80)),
                ('surat_jalan', models.CharField(blank=True, max_length=80)),
                ('tanggal', models.DateField()),
                ('total_rp', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('catatan', models.TextField(blank=True)),
                ('dibatalkan', models.BooleanField(default=False)),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.master')),
            ],
        ),
        migrations.CreateModel(
            name='KirimGudang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tanggal', models.DateField()),
                ('pcs', models.PositiveIntegerField()),
                ('surat_jalan', models.CharField(blank=True, max_length=80)),
                ('catatan', models.TextField(blank=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracking.master')),
                ('gudang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracking.master')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.po')),
            ],
        ),
        migrations.CreateModel(
            name='Hasil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('pcs', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.master')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.po')),
            ],
        ),
        migrations.CreateModel(
            name='Alokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('dibatalkan', 'Dibatalkan')], default='menunggu', max_length=12)),
                ('acc_pada', models.DateTimeField(blank=True, null=True)),
                ('alasan', models.TextField(blank=True)),
                ('acc_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alokasi_acc', to=settings.AUTH_USER_MODEL)),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alokasi_dibuat', to=settings.AUTH_USER_MODEL)),
                ('cmt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.master')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.po')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('urut', models.PositiveIntegerField()),
                ('yard', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('tersedia', 'Tersedia'), ('menunggu', 'Menunggu'), ('siap_kirim', 'Siap kirim'), ('dikirim', 'Dikirim'), ('diterima', 'Diterima'), ('terpakai', 'Terpakai'), ('rusak', 'Rusak')], default='tersedia', max_length=12)),
                ('tgl_kirim', models.DateField(blank=True, null=True)),
                ('sj_kirim', models.CharField(blank=True, max_length=80)),
                ('tgl_terima', models.DateField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True)),
                ('alokasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracking.alokasi')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracking.master')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.invoice')),
                ('lokasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracking.master')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracking.master')),
            ],
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(models.F('vendor'), django.db.models.functions.text.Lower('nomor'), name='invoice_vendor_nomor_ci'),
        ),
        migrations.AddIndex(
            model_name='kirimgudang',
            index=models.Index(fields=['po', 'color'], name='tracking_ki_po_id_25318f_idx'),
        ),
        migrations.AddConstraint(
            model_name='kirimgudang',
            constraint=models.CheckConstraint(condition=models.Q(('pcs__gt', 0)), name='kirim_pcs_positive'),
        ),
        migrations.AddConstraint(
            model_name='hasil',
            constraint=models.UniqueConstraint(fields=('po', 'color'), name='hasil_po_color'),
        ),
        migrations.AddIndex(
            model_name='roll',
            index=models.Index(fields=['status'], name='tracking_ro_status_e8f31a_idx'),
        ),
        migrations.AddIndex(
            model_name='roll',
            index=models.Index(fields=['invoice', 'material', 'color'], name='tracking_ro_invoice_1872d6_idx'),
        ),
        migrations.AddIndex(
            model_name='roll',
            index=models.Index(fields=['alokasi'], name='tracking_ro_alokasi_00760a_idx'),
        ),
        migrations.AddConstraint(
            model_name='roll',
            constraint=models.CheckConstraint(condition=models.Q(('yard__gt', 0)), name='roll_yard_positive'),
        ),
        migrations.AddConstraint(
            model_name='roll',
            constraint=models.UniqueConstraint(fields=('invoice', 'material', 'color', 'urut'), name='roll_urut_unique'),
        ),
    ]
