# Generated by Django 5.2.17 on 2026-09-11 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='shipment_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracking.shipmentline'),
        ),
        migrations.AddConstraint(
            model_name='cmtreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('yards__gte', 0)), name='cmtreceipt_yards_positive'),
        ),
        migrations.AddConstraint(
            model_name='reconciliation',
            constraint=models.CheckConstraint(condition=models.Q(('yards__gte', 0)), name='reconciliation_yards_positive'),
        ),
    ]
