# Generated by Django 5.2.17 on 2026-10-02 01:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('filename', models.CharField(max_length=180)),
                ('content_type', models.CharField(max_length=40)),
                ('size', models.PositiveIntegerField()),
                ('content', models.BinaryField()),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attachment', to='tracking.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
