# Generated by Django 5.2.17 on 2026-10-02 01:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_invoiceattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('urut', models.PositiveSmallIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_groups', to='tracking.invoice')),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracking.po')),
            ],
            options={
                'ordering': ['urut'],
            },
        ),
        migrations.AddField(
            model_name='roll',
            name='invoice_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='tracking.invoicepo'),
        ),
        migrations.AddConstraint(
            model_name='invoicepo',
            constraint=models.CheckConstraint(condition=models.Q(('urut__gte', 1), ('urut__lte', 10)), name='invoice_po_urut_1_10'),
        ),
        migrations.AddConstraint(
            model_name='invoicepo',
            constraint=models.UniqueConstraint(fields=('invoice', 'urut'), name='invoice_po_urut_unique'),
        ),
        migrations.AddConstraint(
            model_name='invoicepo',
            constraint=models.UniqueConstraint(condition=models.Q(('po__isnull', False)), fields=('invoice', 'po'), name='invoice_po_nomor_unique'),
        ),
    ]
