# Generated by Django 5.2.17 on 2026-09-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_immutable_history'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='warehousereceipt',
            name='warehouse_received_positive',
        ),
        migrations.AddConstraint(
            model_name='warehousereceipt',
            constraint=models.CheckConstraint(condition=models.Q(('received__gt', 0), ('discrepancy', True), _connector='OR'), name='warehouse_received_or_discrepancy'),
        ),
    ]
