# Generated by Django 5.2.17 on 2026-10-05 06:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tracking', '0003_invoicepo_roll_invoice_po_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlokasiRoll',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceColor',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ('urut', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['urut', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceMaterial',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ('urut', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['urut', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='alokasi',
            name='sj_kirim',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='alokasi',
            name='tgl_kirim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kirimgudang',
            name='request_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='po',
            name='cmt',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='purchase_orders',
                to='tracking.master',
            ),
        ),
        migrations.AlterField(
            model_name='alokasi',
            name='po',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tracking.po'
            ),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(
                condition=models.Q(('total_rp__gte', 0)), name='invoice_total_nonnegative'
            ),
        ),
        migrations.AddField(
            model_name='alokasiroll',
            name='alokasi',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='items',
                to='tracking.alokasi',
            ),
        ),
        migrations.AddField(
            model_name='alokasiroll',
            name='roll',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='allocation_history',
                to='tracking.roll',
            ),
        ),
        migrations.AddField(
            model_name='invoicecolor',
            name='color',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracking.master'
            ),
        ),
        migrations.AddField(
            model_name='invoicecolor',
            name='lokasi',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='tracking.master',
            ),
        ),
        migrations.AddField(
            model_name='roll',
            name='invoice_color',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='rolls',
                to='tracking.invoicecolor',
            ),
        ),
        migrations.AddField(
            model_name='invoicematerial',
            name='invoice',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='material_groups',
                to='tracking.invoice',
            ),
        ),
        migrations.AddField(
            model_name='invoicematerial',
            name='material',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracking.master'
            ),
        ),
        migrations.AddField(
            model_name='invoicecolor',
            name='group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='color_rows',
                to='tracking.invoicematerial',
            ),
        ),
        migrations.AddConstraint(
            model_name='alokasiroll',
            constraint=models.UniqueConstraint(
                fields=('alokasi', 'roll'), name='alokasi_roll_unique'
            ),
        ),
        migrations.AddConstraint(
            model_name='invoicematerial',
            constraint=models.UniqueConstraint(
                fields=('invoice', 'urut'), name='invoice_material_urut_unique'
            ),
        ),
        migrations.AddConstraint(
            model_name='invoicematerial',
            constraint=models.CheckConstraint(
                condition=models.Q(('urut__gte', 1)), name='invoice_material_urut_positive'
            ),
        ),
        migrations.AddConstraint(
            model_name='invoicecolor',
            constraint=models.UniqueConstraint(
                fields=('group', 'urut'), name='invoice_color_urut_unique'
            ),
        ),
        migrations.AddConstraint(
            model_name='invoicecolor',
            constraint=models.CheckConstraint(
                condition=models.Q(('urut__gte', 1)), name='invoice_color_urut_positive'
            ),
        ),
    ]
