# Generated by Django 5.2.17 on 2026-10-05 06:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tracking', '0005_migrate_material_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceWrite',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ('request_id', models.CharField(max_length=64, unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                (
                    'invoice',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='write_requests',
                        to='tracking.invoice',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
