# Generated by Django 5.2.17 on 2026-10-05 08:59

import django.db.models.deletion
from django.db import migrations, models


def map_unambiguous_materials(apps, schema_editor):
    """Attribute old totals only when their PO/color has one known material."""
    connection = schema_editor.connection
    alias = connection.alias
    Roll = apps.get_model('tracking', 'Roll')
    Hasil = apps.get_model('tracking', 'Hasil')
    KirimGudang = apps.get_model('tracking', 'KirimGudang')
    if connection.vendor == 'postgresql':
        names = sorted(
            apps.get_model('tracking', name)._meta.db_table
            for name in ('Alokasi', 'InvoicePo', 'Roll', 'Hasil', 'KirimGudang')
        )
        quoted = ', '.join(connection.ops.quote_name(name) for name in names)
        with connection.cursor() as cursor:
            cursor.execute(f'LOCK TABLE {quoted} IN SHARE ROW EXCLUSIVE MODE')

    records = (Hasil, KirimGudang)
    old_fields = {
        model: [field.attname for field in model._meta.concrete_fields if field.name != 'material']
        for model in records
    }
    before = {
        model: list(model.objects.using(alias).order_by('pk').values_list(*old_fields[model]))
        for model in records
    }
    pairs = {}
    for allocation_po, legacy_po, material_id, color_id in (
        Roll.objects.using(alias)
        .filter(
            models.Q(alokasi__po__isnull=False)
            | models.Q(alokasi__isnull=True, invoice_po__po__isnull=False)
        )
        .values_list('alokasi__po_id', 'invoice_po__po_id', 'material_id', 'color_id')
        .iterator(chunk_size=1000)
    ):
        pairs.setdefault((allocation_po or legacy_po, color_id), set()).add(material_id)
    for model in records:
        for row in model.objects.using(alias).filter(material_id=None).iterator(chunk_size=1000):
            materials = pairs.get((row.po_id, row.color_id), set())
            if len(materials) == 1:
                model.objects.using(alias).filter(pk=row.pk).update(
                    material_id=next(iter(materials))
                )
    after = {
        model: list(model.objects.using(alias).order_by('pk').values_list(*old_fields[model]))
        for model in records
    }
    if before != after:
        raise RuntimeError('Pemetaan bahan mengubah data hasil atau kiriman historis.')


class Migration(migrations.Migration):
    dependencies = [
        ('tracking', '0006_invoice_write_requests'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hasil',
            name='hasil_po_color',
        ),
        migrations.AddField(
            model_name='hasil',
            name='material',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='tracking.master',
            ),
        ),
        migrations.AddField(
            model_name='kirimgudang',
            name='material',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='tracking.master',
            ),
        ),
        migrations.AddIndex(
            model_name='kirimgudang',
            index=models.Index(
                fields=['po', 'material', 'color'], name='tracking_ki_po_id_3bfeb1_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='hasil',
            constraint=models.UniqueConstraint(
                fields=('po', 'material', 'color'), name='hasil_po_material_color'
            ),
        ),
        migrations.AddConstraint(
            model_name='hasil',
            constraint=models.UniqueConstraint(
                condition=models.Q(('material__isnull', True)),
                fields=('po', 'color'),
                name='hasil_po_color_legacy',
            ),
        ),
        migrations.RunPython(map_unambiguous_materials, migrations.RunPython.noop),
    ]
