# Generated by Django 5.2.17 on 2026-10-08 01:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_production_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasil',
            name='sizes_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HasilUkuran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('label', models.CharField(max_length=80)),
                ('key', models.CharField(max_length=80)),
                ('pcs', models.PositiveIntegerField()),
                ('urut', models.PositiveIntegerField(default=0)),
                ('hasil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizes', to='tracking.hasil')),
            ],
            options={
                'ordering': ['urut', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='KirimUkuran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('pcs', models.PositiveIntegerField()),
                ('kiriman', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizes', to='tracking.kirimgudang')),
                ('ukuran', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='tracking.hasilukuran')),
            ],
        ),
        migrations.AddConstraint(
            model_name='hasilukuran',
            constraint=models.UniqueConstraint(fields=('hasil', 'key'), name='hasil_size_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='hasilukuran',
            constraint=models.CheckConstraint(condition=models.Q(('key', ''), _negated=True), name='hasil_size_key_required'),
        ),
        migrations.AddConstraint(
            model_name='kirimukuran',
            constraint=models.UniqueConstraint(fields=('kiriman', 'ukuran'), name='shipment_size_unique'),
        ),
        migrations.AddConstraint(
            model_name='kirimukuran',
            constraint=models.CheckConstraint(condition=models.Q(('pcs__gt', 0)), name='shipment_size_positive'),
        ),
    ]
